# Generated by Django 6.1 on 2026-09-12 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_key",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Раздел"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название шаблона"),
                ),
                ("columns", models.JSONField(default=list, verbose_name="Колонки")),
                (
                    "fmt",
                    models.CharField(
                        choices=[("csv", "CSV"), ("xlsx", "XLSX")],
                        default="csv",
                        max_length=10,
                        verbose_name="Формат по умолчанию",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон экспорта",
                "verbose_name_plural": "Шаблоны экспорта",
                "ordering": ["model_key", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("model_key", "name"),
                        name="unique_export_template_name_per_model",
                    )
                ],
            },
        ),
    ]
