# Generated by Django 6.1 on 2026-10-10 15:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academy", "0023_backfill_trainer_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeSalaryProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Пусто — должность из профиля тренера или роль пользователя.",
                        max_length=100,
                        verbose_name="Должность",
                    ),
                ),
                (
                    "salary_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Фиксированный оклад"),
                            ("REVENUE_PERCENT", "Процент от оплаты студентов"),
                            ("PER_STUDENT", "За активного студента"),
                            ("PER_GROUP", "За группу"),
                            ("COMBINED", "Комбинированная схема"),
                        ],
                        max_length=20,
                        verbose_name="Тип оплаты",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="KGS",
                        editable=False,
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активна"
                    ),
                ),
                ("effective_from", models.DateField(verbose_name="Действует с")),
                (
                    "effective_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="Действует по"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salary_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зарплатный профиль",
                "verbose_name_plural": "Зарплатные профили",
                "ordering": ["employee__last_name", "employee__first_name"],
            },
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Черновик"),
                            ("CALCULATED", "Рассчитан"),
                            ("RETURNED", "Возвращён на исправление"),
                            ("APPROVED", "Утверждён"),
                            ("PARTIALLY_PAID", "Частично выплачен"),
                            ("PAID", "Выплачен"),
                            ("VOID", "Аннулирован"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "total_accrued",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "total_adjustments",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "total_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "amount_due",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "warnings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Предупреждения последнего расчёта.",
                    ),
                ),
                (
                    "errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ошибки, блокирующие утверждение.",
                    ),
                ),
                (
                    "salary_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FIXED", "Фиксированный оклад"),
                            ("REVENUE_PERCENT", "Процент от оплаты студентов"),
                            ("PER_STUDENT", "За активного студента"),
                            ("PER_GROUP", "За группу"),
                            ("COMBINED", "Комбинированная схема"),
                        ],
                        max_length=20,
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=100)),
                (
                    "active_students",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Число разных активных студентов в периоде — если применимо.",
                        null=True,
                    ),
                ),
                ("return_reason", models.TextField(blank=True)),
                ("calculated_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payrolls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Расчёт зарплаты",
                "verbose_name_plural": "Расчёты зарплаты",
                "ordering": [
                    "-period__year",
                    "-period__month",
                    "-period__period_type",
                    "employee__last_name",
                ],
            },
        ),
        migrations.CreateModel(
            name="PayrollAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("BONUS", "Премия / доплата"),
                            ("DEDUCTION", "Удержание"),
                            ("CORRECTION", "Исправление"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Со знаком: удержание всегда отрицательное, премия — положительная.",
                        max_digits=14,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Ожидает утверждения"),
                            ("APPLIED", "Применена"),
                            ("REJECTED", "Отклонена"),
                            ("VOID", "Отменена"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payroll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="accounting.payroll",
                    ),
                ),
            ],
            options={
                "verbose_name": "Корректировка",
                "verbose_name_plural": "Корректировки",
                "ordering": ["payroll", "id"],
            },
        ),
        migrations.CreateModel(
            name="PayrollAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(db_index=True, max_length=40)),
                ("entity_id", models.PositiveBigIntegerField(db_index=True)),
                ("action", models.CharField(db_index=True, max_length=40)),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payroll",
                    models.ForeignKey(
                        blank=True,
                        help_text="Расчёт, к которому относится запись (для истории на странице расчёта).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_entries",
                        to="accounting.payroll",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись журнала аудита",
                "verbose_name_plural": "Журнал аудита бухгалтерии",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PayrollPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2100),
                        ]
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("FIRST_HALF", "1–15"),
                            ("SECOND_HALF", "16–конец месяца"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(editable=False)),
                ("end_date", models.DateField(editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Черновик"),
                            ("CALCULATED", "Рассчитан"),
                            ("APPROVED", "Утверждён"),
                            ("CLOSED", "Закрыт"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Расчётный период",
                "verbose_name_plural": "Расчётные периоды",
                "ordering": ["-year", "-month", "-period_type"],
            },
        ),
        migrations.AddField(
            model_name="payroll",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payrolls",
                to="accounting.payrollperiod",
            ),
        ),
        migrations.CreateModel(
            name="SalaryRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Оклад"),
                            ("REVENUE_PERCENT", "Процент от оплаты студентов"),
                            ("PER_STUDENT", "За активного студента"),
                            ("PER_GROUP", "За группу"),
                            ("BONUS", "Дополнительное начисление"),
                        ],
                        max_length=20,
                        verbose_name="Тип правила",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Оклад в месяц, ставка за студента в месяц, ставка за группу в месяц или сумма бонуса.",
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Сумма / ставка, сом",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Процент",
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        choices=[
                            (
                                "SPLIT",
                                "Доля месячной суммы в каждой половине (по умолчанию 50/50)",
                            ),
                            ("PRORATE_DAYS", "Пропорционально календарным дням"),
                            ("STUDENT_DAYS", "По дням активности каждого студента"),
                            (
                                "SNAPSHOT",
                                "По числу студентов на контрольную дату (конец периода)",
                            ),
                            ("STANDARD", "Стандартный"),
                        ],
                        max_length=20,
                        verbose_name="Метод расчёта",
                    ),
                ),
                (
                    "first_half_share",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        help_text="Для метода SPLIT: остаток — во второй половине.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Доля первой половины, %",
                    ),
                ),
                (
                    "revenue_basis",
                    models.CharField(
                        choices=[
                            (
                                "RECEIVED",
                                "Фактически полученные платежи (по дате поступления)",
                            ),
                            (
                                "ALLOCATED",
                                "Распределённая выручка (по дням периода обучения)",
                            ),
                        ],
                        default="RECEIVED",
                        max_length=20,
                        verbose_name="База процента",
                    ),
                ),
                (
                    "refund_policy",
                    models.CharField(
                        choices=[
                            (
                                "DEDUCT",
                                "Вычитать в периоде возврата (со ссылкой на исходный платёж)",
                            ),
                            ("IGNORE", "Не учитывать возвраты в зарплате"),
                        ],
                        default="DEDUCT",
                        max_length=20,
                        verbose_name="Учёт возвратов",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Комментарий"
                    ),
                ),
                ("effective_from", models.DateField(verbose_name="Действует с")),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Действует по (включительно)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активно"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rules",
                        to="accounting.employeesalaryprofile",
                        verbose_name="Профиль",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salary_rules",
                        to="academy.group",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "previous_version",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="next_version",
                        to="accounting.salaryrule",
                        verbose_name="Предыдущая версия",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salary_rules",
                        to="academy.course",
                        verbose_name="Программа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Правило начисления",
                "verbose_name_plural": "Правила начисления",
                "ordering": ["employee_profile", "rule_type", "-effective_from", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PayrollLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Оклад"),
                            ("REVENUE_PERCENT", "Процент от оплаты"),
                            ("REFUND_CORRECTION", "Корректировка возврата"),
                            ("PER_STUDENT", "За активных студентов"),
                            ("PER_GROUP", "За группу"),
                            ("BONUS", "Дополнительное начисление"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("source_type", models.CharField(blank=True, max_length=40)),
                ("source_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payroll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounting.payroll",
                    ),
                ),
                (
                    "salary_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.salaryrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка расчёта",
                "verbose_name_plural": "Строки расчёта",
                "ordering": ["payroll", "id"],
            },
        ),
        migrations.CreateModel(
            name="StudentPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("payment", "Оплата"), ("refund", "Возврат")],
                        default="payment",
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Всегда положительная; для возврата знак задаёт тип операции.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Сумма, сом",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="KGS",
                        editable=False,
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "received_date",
                    models.DateField(
                        db_index=True, verbose_name="Дата поступления / возврата"
                    ),
                ),
                ("service_start", models.DateField(verbose_name="Обучение с")),
                ("service_end", models.DateField(verbose_name="Обучение по")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Наличные"),
                            ("bank", "Банковский перевод"),
                            ("card", "Карта / QR"),
                            ("other", "Другое"),
                        ],
                        default="cash",
                        max_length=10,
                        verbose_name="Способ",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Номер документа"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "status",
                    models.CharField(
                        choices=[("confirmed", "Подтверждён"), ("void", "Отменён")],
                        db_index=True,
                        default="confirmed",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "void_reason",
                    models.TextField(blank=True, verbose_name="Причина отмены"),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "voided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отменено"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Заполняется автоматически из группы.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_payments",
                        to="academy.course",
                        verbose_name="Программа",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто внёс",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Группа, за обучение в которой оплачено.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_payments",
                        to="academy.group",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "refund_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="accounting.studentpayment",
                        verbose_name="Возврат по платежу",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="academy.student",
                        verbose_name="Студент",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто отменил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёж студента",
                "verbose_name_plural": "Платежи студентов",
                "ordering": ["-received_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PayrollPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank", "Банковский перевод"),
                            ("cash", "Наличные"),
                            ("other", "Другое"),
                        ],
                        default="bank",
                        max_length=10,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("comment", models.TextField(blank=True)),
                (
                    "is_advance",
                    models.BooleanField(default=False, verbose_name="Аванс"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("CONFIRMED", "Подтверждена"), ("VOID", "Отменена")],
                        db_index=True,
                        default="CONFIRMED",
                        max_length=10,
                    ),
                ),
                ("void_reason", models.TextField(blank=True)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payroll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="accounting.payroll",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Выплата сотруднику",
                "verbose_name_plural": "Выплаты сотрудникам",
                "ordering": ["payroll", "payment_date", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="payroll_payment_amount_positive",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="payrollperiod",
            constraint=models.UniqueConstraint(
                fields=("year", "month", "period_type"), name="unique_payroll_period"
            ),
        ),
        migrations.AddConstraint(
            model_name="payroll",
            constraint=models.UniqueConstraint(
                fields=("period", "employee"), name="unique_payroll_employee_period"
            ),
        ),
        migrations.AddIndex(
            model_name="salaryrule",
            index=models.Index(
                fields=["employee_profile", "is_active"], name="ix_srule_profile_active"
            ),
        ),
        migrations.AddIndex(
            model_name="studentpayment",
            index=models.Index(
                fields=["group", "received_date"], name="ix_stpay_group_date"
            ),
        ),
        migrations.AddIndex(
            model_name="studentpayment",
            index=models.Index(
                fields=["course", "received_date"], name="ix_stpay_course_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentpayment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="student_payment_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentpayment",
            constraint=models.CheckConstraint(
                condition=models.Q(("service_end__gte", models.F("service_start"))),
                name="student_payment_service_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentpayment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "refund"), ("refund_of__isnull", False)),
                    models.Q(("kind", "payment"), ("refund_of__isnull", True)),
                    _connector="OR",
                ),
                name="student_payment_refund_link",
            ),
        ),
    ]
