# Generated by Django 6.1 on 2026-10-10 15:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0023_backfill_trainer_history"),
        ("accounting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeesalaryprofile",
            name="salary_type",
            field=models.CharField(
                choices=[
                    ("FIXED", "Фиксированный оклад"),
                    ("PERCENT", "Процент от стоимости курса"),
                    ("REVENUE_PERCENT", "Процент от оплаты студентов (устар.)"),
                    ("PER_STUDENT", "За активного студента (устар.)"),
                    ("PER_GROUP", "За группу (устар.)"),
                    ("COMBINED", "Комбинированная схема (устар.)"),
                ],
                max_length=20,
                verbose_name="Тип оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="salary_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FIXED", "Фиксированный оклад"),
                    ("PERCENT", "Процент от стоимости курса"),
                    ("REVENUE_PERCENT", "Процент от оплаты студентов (устар.)"),
                    ("PER_STUDENT", "За активного студента (устар.)"),
                    ("PER_GROUP", "За группу (устар.)"),
                    ("COMBINED", "Комбинированная схема (устар.)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payrollline",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("FIXED", "Оклад"),
                    ("PERCENT", "Процент за завершённый цикл курса"),
                    ("REVENUE_PERCENT", "Процент от оплаты"),
                    ("REFUND_CORRECTION", "Корректировка возврата"),
                    ("PER_STUDENT", "За активных студентов"),
                    ("PER_GROUP", "За группу"),
                    ("BONUS", "Дополнительное начисление"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="salaryrule",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("FIXED", "Оклад"),
                    ("PERCENT", "Процент от стоимости курса"),
                    ("REVENUE_PERCENT", "Процент от оплаты студентов (устар.)"),
                    ("PER_STUDENT", "За активного студента (устар.)"),
                    ("PER_GROUP", "За группу (устар.)"),
                    ("BONUS", "Дополнительное начисление (устар.)"),
                ],
                max_length=20,
                verbose_name="Тип правила",
            ),
        ),
        migrations.CreateModel(
            name="CourseCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(verbose_name="Номер цикла в группе"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("IN_PROGRESS", "Идёт"), ("COMPLETED", "Завершён")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("required_lessons", models.PositiveSmallIntegerField()),
                ("lessons_done", models.PositiveSmallIntegerField(default=0)),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Дата первого урока цикла.", null=True
                    ),
                ),
                (
                    "completed_on",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Дата проведения последнего необходимого урока.",
                        null=True,
                    ),
                ),
                (
                    "last_lesson_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("student_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "student_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Основание (только id студентов).",
                    ),
                ),
                ("student_count_rule", models.CharField(blank=True, max_length=20)),
                (
                    "course_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_cycles",
                        to="academy.course",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_cycles",
                        to="academy.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цикл курса",
                "verbose_name_plural": "Циклы курсов",
                "ordering": ["group", "number"],
            },
        ),
        migrations.CreateModel(
            name="CoursePayrollSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_per_student",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Стоимость курса за студента, сом",
                    ),
                ),
                (
                    "required_lessons",
                    models.PositiveSmallIntegerField(
                        help_text="Сколько проведённых уроков завершают расчётный цикл (например 12 или 20).",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Уроков в цикле",
                    ),
                ),
                (
                    "count_lessons_from",
                    models.DateField(
                        help_text="Уроки до этой даты в циклы не входят (старт учёта в бухгалтерии).",
                        verbose_name="Учитывать уроки с",
                    ),
                ),
                (
                    "student_count_rule",
                    models.CharField(
                        choices=[
                            (
                                "ON_COMPLETION",
                                "Активные в группе на дату завершения цикла",
                            ),
                            (
                                "DURING_CYCLE",
                                "Активные в группе хотя бы один день цикла",
                            ),
                        ],
                        default="ON_COMPLETION",
                        max_length=20,
                        verbose_name="Правило учёта студентов",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активны"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_settings",
                        to="academy.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зарплатные настройки курса",
                "verbose_name_plural": "Зарплатные настройки курсов",
                "ordering": ["course__name"],
            },
        ),
        migrations.CreateModel(
            name="CycleAccrual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lessons", models.PositiveSmallIntegerField()),
                ("completed_on", models.DateField()),
                ("student_count", models.PositiveIntegerField()),
                ("course_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accruals",
                        to="accounting.coursecycle",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycle_accrual",
                        to="accounting.payrollline",
                    ),
                ),
                (
                    "payroll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cycle_accruals",
                        to="accounting.payroll",
                    ),
                ),
                (
                    "salary_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.salaryrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Начисление за цикл",
                "verbose_name_plural": "Начисления за циклы",
            },
        ),
        migrations.AddConstraint(
            model_name="coursecycle",
            constraint=models.UniqueConstraint(
                fields=("group", "course", "number"), name="unique_course_cycle"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecycle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "IN_PROGRESS")),
                fields=("group", "course"),
                name="unique_open_course_cycle",
            ),
        ),
        migrations.AddConstraint(
            model_name="cycleaccrual",
            constraint=models.UniqueConstraint(
                fields=("cycle", "employee"), name="unique_cycle_accrual"
            ),
        ),
    ]
