# Generated by Django 6.1 on 2026-10-10 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def fill_thresholds(apps, schema_editor):
    """Накопленный порог существующих циклов и статус существующих начислений."""
    CourseCycle = apps.get_model("accounting", "CourseCycle")
    CycleAccrual = apps.get_model("accounting", "CycleAccrual")
    totals = {}
    for cycle in CourseCycle.objects.order_by("group_id", "course_id", "number"):
        key = (cycle.group_id, cycle.course_id)
        done = totals.get(key, 0)
        if cycle.status == "COMPLETED":
            done += cycle.required_lessons
            totals[key] = done
            cycle.lessons_total = done
        else:
            cycle.lessons_total = done + cycle.lessons_done
        cycle.save(update_fields=["lessons_total"])
    locked = ("APPROVED", "PARTIALLY_PAID", "PAID")
    for accrual in CycleAccrual.objects.select_related("cycle", "payroll"):
        accrual.lessons_total = accrual.cycle.lessons_total
        accrual.status = "APPROVED" if accrual.payroll and accrual.payroll.status in locked else "ACCRUED"
        accrual.save(update_fields=["lessons_total", "status"])


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0023_backfill_trainer_history"),
        ("accounting", "0002_percent_of_course_cycles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cycleaccrual",
            options={
                "ordering": ["-completed_on", "id"],
                "verbose_name": "Начисление за цикл",
                "verbose_name_plural": "Начисления за циклы",
            },
        ),
        migrations.RemoveConstraint(
            model_name="coursecycle",
            name="unique_course_cycle",
        ),
        migrations.AddField(
            model_name="coursecycle",
            name="invalidated_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="coursecycle",
            name="lessons_total",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Накопленное число проведённых уроков группы на пороге цикла (12, 24, 36…).",
            ),
        ),
        migrations.AddField(
            model_name="cycleaccrual",
            name="adjustment",
            field=models.ForeignKey(
                blank=True,
                help_text="Корректировка, сторнирующая это начисление.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.payrolladjustment",
            ),
        ),
        migrations.AddField(
            model_name="cycleaccrual",
            name="lessons_total",
            field=models.PositiveIntegerField(
                default=0, help_text="Порог: накопленные уроки группы."
            ),
        ),
        migrations.AddField(
            model_name="cycleaccrual",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="cycleaccrual",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACCRUED", "Начислено"),
                    ("APPROVED", "Утверждено"),
                    ("CANCELLED", "Отменено (уроки исправлены до утверждения)"),
                    ("CORRECTED", "Сторнировано корректировкой"),
                    ("CORRECTION_REQUIRED", "Требует ручной корректировки"),
                ],
                db_index=True,
                default="ACCRUED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cycleaccrual",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="coursecycle",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "Идёт"),
                    ("COMPLETED", "Завершён"),
                    ("INVALIDATED", "Отменён (уроки исправлены)"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="coursepayrollsettings",
            name="count_lessons_from",
            field=models.DateField(
                blank=True,
                help_text="Необязательно. Пусто — учёт с первого проведённого урока группы.",
                null=True,
                verbose_name="Учитывать уроки с",
            ),
        ),
        migrations.AlterField(
            model_name="cycleaccrual",
            name="lessons",
            field=models.PositiveSmallIntegerField(help_text="Уроков в цикле."),
        ),
        migrations.AlterField(
            model_name="cycleaccrual",
            name="line",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cycle_accrual",
                to="accounting.payrollline",
            ),
        ),
        migrations.AlterField(
            model_name="cycleaccrual",
            name="payroll",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cycle_accruals",
                to="accounting.payroll",
            ),
        ),
        migrations.AlterField(
            model_name="payrolladjustment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Пусто — создана системой (автокорректировка после исправления уроков).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecycle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "INVALIDATED"), _negated=True),
                fields=("group", "course", "number"),
                name="unique_course_cycle",
            ),
        ),
        migrations.RunPython(fill_thresholds, migrations.RunPython.noop),
    ]
