# Generated by Django 6.1 on 2026-10-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_automatic_cycle_accruals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payrollline",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("FIXED", "Оклад"),
                    ("PERCENT", "Процент за завершённый цикл курса"),
                    ("REVENUE_PERCENT", "Процент от оплаты"),
                    ("REFUND_CORRECTION", "Корректировка возврата"),
                    ("PRIOR_FIXED", "Зачёт оклада, начисленного по прежней схеме"),
                    ("PER_STUDENT", "За активных студентов"),
                    ("PER_GROUP", "За группу"),
                    ("BONUS", "Дополнительное начисление"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="period_type",
            field=models.CharField(
                choices=[
                    ("FIRST_HALF", "1–15"),
                    ("SECOND_HALF", "16–конец месяца"),
                    ("MONTH", "Весь месяц (оклад)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="salaryrule",
            name="calculation_method",
            field=models.CharField(
                choices=[
                    ("MONTHLY", "Полный месячный оклад"),
                    (
                        "SPLIT",
                        "Доля месячной суммы в каждой половине (по умолчанию 50/50)",
                    ),
                    ("PRORATE_DAYS", "Пропорционально календарным дням"),
                    ("STUDENT_DAYS", "По дням активности каждого студента"),
                    (
                        "SNAPSHOT",
                        "По числу студентов на контрольную дату (конец периода)",
                    ),
                    ("STANDARD", "Стандартный"),
                ],
                max_length=20,
                verbose_name="Метод расчёта",
            ),
        ),
    ]
