"""История тарифов, связь уроков с циклами, проверка спорных начислений,
направления сотрудников.

Только добавляет таблицы и поля; существующие финансовые записи не
меняются и не удаляются. Перенос данных — в 0006 (отдельной транзакцией),
повторяемо и без дублей:

* каждой настройке курса — первая версия тарифа с её текущей ценой,
  помеченная `is_migrated` (дата начала неизвестна — тариф действует на всю
  предшествующую историю, как и раньше; проверить в «Стоимость курсов»);
* завершённым циклам — привязка уроков, восстановленная по текущим
  проведённым урокам группы (`backfilled`), только если она однозначна
  (число уроков и последний урок цикла совпадают); остальные циклы
  показывает `manage.py payroll_reconcile` для ручной проверки.

Направление (`department`) в старых расчётах не заполняется: аналитика берёт
направление из профиля сотрудника, пока бухгалтер не укажет его.
"""
# Generated by Django 6.1 on 2026-10-10 19:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0023_backfill_trainer_history"),
        ("accounting", "0004_monthly_fixed_salary"),
        ("users", "0005_accountant_director_roles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coursepayrollsettings",
            name="counted_subjects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Только уроки этих предметов входят в цикл (например, только IT). Пусто — все уроки группы.",
                related_name="+",
                to="users.subject",
                verbose_name="Учитываемые предметы",
            ),
        ),
        migrations.AddField(
            model_name="cycleaccrual",
            name="review_reasons",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Почему начисление требует проверки.",
            ),
        ),
        migrations.AddField(
            model_name="cycleaccrual",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cycleaccrual",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeesalaryprofile",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IT", "IT"),
                    ("SOFT_SKILLS", "Soft Skills"),
                    ("ENGLISH", "Английский"),
                    ("TEAM_LEAD", "Тимлиды"),
                    ("ASSISTANT", "Ассистенты"),
                    ("OTHER", "Прочий персонал"),
                ],
                help_text="Пусто — по роли: Team Lead, Ассистент, иначе «Прочий персонал».",
                max_length=20,
                verbose_name="Направление",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IT", "IT"),
                    ("SOFT_SKILLS", "Soft Skills"),
                    ("ENGLISH", "Английский"),
                    ("TEAM_LEAD", "Тимлиды"),
                    ("ASSISTANT", "Ассистенты"),
                    ("OTHER", "Прочий персонал"),
                ],
                db_index=True,
                help_text="Снимок направления сотрудника на момент расчёта (для аналитики).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cycleaccrual",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACCRUED", "Начислено"),
                    ("APPROVED", "Утверждено"),
                    ("CANCELLED", "Отменено (уроки исправлены до утверждения)"),
                    ("CORRECTED", "Сторнировано корректировкой"),
                    ("CORRECTION_REQUIRED", "Требует ручной корректировки"),
                    ("REVIEW_REQUIRED", "Требует проверки"),
                ],
                db_index=True,
                default="ACCRUED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Пусто — период создан автоматически (manage.py payroll_autorun).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CoursePriceVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_per_student",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Стоимость за студента в месяц, сом",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="KGS",
                        editable=False,
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                ("effective_from", models.DateField(verbose_name="Действует с")),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Действует по (включительно)",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Причина изменения")),
                (
                    "is_migrated",
                    models.BooleanField(
                        default=False,
                        help_text="Цена из настроек курса до введения истории тарифов: дата начала неизвестна — проверьте.",
                        verbose_name="Перенесена из прежних настроек",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_versions",
                        to="academy.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор изменения",
                    ),
                ),
                (
                    "previous_version",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="next_version",
                        to="accounting.coursepriceversion",
                        verbose_name="Предыдущая версия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тариф курса",
                "verbose_name_plural": "История тарифов курсов",
                "ordering": ["course", "-effective_from", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("course", "effective_from"),
                        name="unique_course_price_start",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("effective_to__isnull", True)),
                        fields=("course",),
                        name="unique_open_course_price",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("price_per_student__gt", 0)),
                        name="course_price_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gte", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="course_price_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CycleLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lesson_ref",
                    models.PositiveBigIntegerField(
                        help_text="id урока (сохраняется, даже если урок удалён)."
                    ),
                ),
                ("lesson_date", models.DateField()),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        help_text="Порядковый номер урока в цикле, с 1."
                    ),
                ),
                ("is_live", models.BooleanField(db_index=True, default=True)),
                (
                    "backfilled",
                    models.BooleanField(
                        default=False,
                        help_text="Восстановлено миграцией по текущим урокам.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cycle_lessons",
                        to="accounting.coursecycle",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payroll_cycle_links",
                        to="academy.lesson",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        help_text="Тренер, фактически проводивший урок.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок цикла",
                "verbose_name_plural": "Уроки циклов",
                "ordering": ["cycle", "position"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_live", True)),
                        fields=("lesson_ref",),
                        name="unique_live_cycle_lesson",
                    ),
                    models.UniqueConstraint(
                        fields=("cycle", "position"),
                        name="unique_cycle_lesson_position",
                    ),
                ],
            },
        ),
    ]
