# Generated by Django 6.1 on 2026-09-10 03:44

import apps.users.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название направления или предмета. Например: Python, Frontend, Backend, JavaScript.', max_length=100, unique=True, verbose_name='Название предмета')),
                ('description', models.TextField(blank=True, help_text='Краткое описание предмета.', verbose_name='Описание')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Можно ли назначать этот предмет новым группам.', verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания предмета.', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения предмета.', verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(help_text='Уникальный логин пользователя для входа в систему.', max_length=150, unique=True, verbose_name='Логин')),
                ('email', models.EmailField(help_text='Уникальный адрес электронной почты пользователя.', max_length=254, unique=True, verbose_name='Электронная почта')),
                ('first_name', models.CharField(help_text='Имя пользователя.', max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Фамилия пользователя.', max_length=100, verbose_name='Фамилия')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('teacher', 'Тренер')], db_index=True, default='teacher', help_text='Определяет права доступа пользователя в системе.', max_length=20, verbose_name='Роль')),
                ('is_verified', models.BooleanField(default=False, help_text='Подтверждён ли аккаунт администратором.', verbose_name='Аккаунт подтверждён')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания аккаунта.', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения аккаунта.', verbose_name='Дата обновления')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', apps.users.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='Контактный номер телефона тренера.', max_length=30, verbose_name='Номер телефона')),
                ('image', models.ImageField(blank=True, help_text='Фотография профиля тренера.', null=True, upload_to='teachers/', verbose_name='Фотография')),
                ('position', models.CharField(default='Тренер', help_text='Должность тренера в OkurmenKIDS.', max_length=100, verbose_name='Должность')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, help_text='Количество лет преподавательского опыта.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='Опыт работы')),
                ('bio', models.TextField(blank=True, help_text='Краткая информация о тренере.', verbose_name='О тренере')),
                ('hire_date', models.DateField(blank=True, help_text='Дата начала работы тренера в OkurmenKIDS.', null=True, verbose_name='Дата начала работы')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Может ли тренер работать с группами.', verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания профиля.', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения профиля.', verbose_name='Дата обновления')),
                ('subjects', models.ManyToManyField(blank=True, help_text='Предметы, которые преподаёт тренер.', related_name='teachers', to='users.subject', verbose_name='Предметы')),
                ('user', models.OneToOneField(help_text='Аккаунт пользователя, связанный с профилем тренера.', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
                'ordering': ['-created_at'],
            },
        ),
    ]
