# Generated by Django 6.1 on 2026-10-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_role_team_lead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Администратор"),
                    ("teacher", "Тренер"),
                    ("team_lead", "Team Lead"),
                    ("assistant", "Ассистент"),
                ],
                db_index=True,
                default="teacher",
                help_text="Определяет права доступа пользователя в системе.",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
    ]
