# Generated by Django 6.1 on 2026-09-10 10:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Вместимость",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Описание"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активна"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Аудитория",
                "verbose_name_plural": "Аудитории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "count_lesson",
                    models.PositiveSmallIntegerField(
                        help_text="Общее число занятий в полном учебном плане курса.",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Количество занятий",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        help_text="Предметы, которые входят в курс (любое распределение).",
                        related_name="courses",
                        to="users.subject",
                        verbose_name="Предметы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CourseLessonPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lesson_number",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Номер занятия",
                    ),
                ),
                ("topic", models.CharField(max_length=255, verbose_name="Тема")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "youtube_url",
                    models.URLField(blank=True, verbose_name="Ссылка на YouTube"),
                ),
                (
                    "presentation_urls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Список URL.",
                        verbose_name="Ссылки на презентации",
                    ),
                ),
                (
                    "homework_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Название домашнего задания",
                    ),
                ),
                (
                    "homework_description",
                    models.TextField(
                        blank=True, verbose_name="Описание домашнего задания"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_plans",
                        to="academy.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lesson_plans",
                        to="users.subject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "План занятия",
                "verbose_name_plural": "Планы занятий",
                "ordering": ["course", "lesson_number"],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Название группы"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Время начала")),
                ("end_time", models.TimeField(verbose_name="Время окончания")),
                (
                    "days_of_week",
                    models.JSONField(
                        default=list,
                        help_text="Например: ['mon', 'wed', 'fri'].",
                        verbose_name="Дни недели",
                    ),
                ),
                (
                    "max_students",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Максимум студентов",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активна"),
                            ("paused", "Приостановлена"),
                            ("completed", "Завершена"),
                            ("cancelled", "Отменена"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="groups",
                        to="academy.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="groups",
                        to="users.teacher",
                        verbose_name="Тренер",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="groups",
                        to="academy.room",
                        verbose_name="Аудитория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
                "ordering": ["-start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="KPIAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField(verbose_name="Период с")),
                ("date_to", models.DateField(verbose_name="Период по")),
                (
                    "total_records",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего записей"
                    ),
                ),
                (
                    "present_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Присутствовал"
                    ),
                ),
                (
                    "absent_count",
                    models.PositiveIntegerField(default=0, verbose_name="Отсутствовал"),
                ),
                (
                    "late_count",
                    models.PositiveIntegerField(default=0, verbose_name="Опозданий"),
                ),
                (
                    "excused_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Уважительная причина"
                    ),
                ),
                (
                    "attendance_percent",
                    models.FloatField(default=0, verbose_name="Посещаемость, %"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_kpi_records",
                        to="academy.group",
                        verbose_name="Группа",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI посещаемости",
                "verbose_name_plural": "KPI посещаемости",
                "ordering": ["-date_to"],
            },
        ),
        migrations.CreateModel(
            name="KPIGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField(verbose_name="Период с")),
                ("date_to", models.DateField(verbose_name="Период по")),
                (
                    "total_students",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего студентов"
                    ),
                ),
                (
                    "total_lessons",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего занятий"
                    ),
                ),
                (
                    "completed_lessons",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Проведено занятий"
                    ),
                ),
                (
                    "cancelled_lessons",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Отменено занятий"
                    ),
                ),
                (
                    "attendance_percent",
                    models.FloatField(default=0, verbose_name="Посещаемость, %"),
                ),
                (
                    "homework_completion_percent",
                    models.FloatField(default=0, verbose_name="Выполнение ДЗ, %"),
                ),
                (
                    "average_score",
                    models.FloatField(default=0, verbose_name="Средний балл"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_records",
                        to="academy.group",
                        verbose_name="Группа",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI группы",
                "verbose_name_plural": "KPI групп",
                "ordering": ["-date_to"],
            },
        ),
        migrations.CreateModel(
            name="KPIHomework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField(verbose_name="Период с")),
                ("date_to", models.DateField(verbose_name="Период по")),
                (
                    "total_homeworks",
                    models.PositiveIntegerField(default=0, verbose_name="Всего ДЗ"),
                ),
                (
                    "total_results",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего результатов"
                    ),
                ),
                (
                    "submitted_count",
                    models.PositiveIntegerField(default=0, verbose_name="Сдано"),
                ),
                (
                    "checked_count",
                    models.PositiveIntegerField(default=0, verbose_name="Проверено"),
                ),
                (
                    "not_submitted_count",
                    models.PositiveIntegerField(default=0, verbose_name="Не сдано"),
                ),
                (
                    "late_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Сдано с опозданием"
                    ),
                ),
                (
                    "completion_percent",
                    models.FloatField(default=0, verbose_name="Выполнение, %"),
                ),
                (
                    "average_score",
                    models.FloatField(default=0, verbose_name="Средний балл"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_kpi_records",
                        to="academy.group",
                        verbose_name="Группа",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI домашних заданий",
                "verbose_name_plural": "KPI домашних заданий",
                "ordering": ["-date_to"],
            },
        ),
        migrations.CreateModel(
            name="KPITeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField(verbose_name="Период с")),
                ("date_to", models.DateField(verbose_name="Период по")),
                (
                    "total_groups",
                    models.PositiveIntegerField(default=0, verbose_name="Всего групп"),
                ),
                (
                    "total_lessons",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего занятий"
                    ),
                ),
                (
                    "completed_lessons",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Проведено занятий"
                    ),
                ),
                (
                    "cancelled_lessons",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Отменено занятий"
                    ),
                ),
                (
                    "attendance_percent",
                    models.FloatField(default=0, verbose_name="Посещаемость, %"),
                ),
                (
                    "homework_completion_percent",
                    models.FloatField(default=0, verbose_name="Выполнение ДЗ, %"),
                ),
                (
                    "average_student_score",
                    models.FloatField(default=0, verbose_name="Средний балл студентов"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_records",
                        to="users.teacher",
                        verbose_name="Тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI тренера",
                "verbose_name_plural": "KPI тренеров",
                "ordering": ["-date_to"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lesson_number",
                    models.PositiveSmallIntegerField(verbose_name="Номер занятия"),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("start_time", models.TimeField(verbose_name="Время начала")),
                ("end_time", models.TimeField(verbose_name="Время окончания")),
                (
                    "topic",
                    models.CharField(blank=True, max_length=255, verbose_name="Тема"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "youtube_url",
                    models.URLField(blank=True, verbose_name="Ссылка на YouTube"),
                ),
                (
                    "presentation_urls",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Ссылки на презентации"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Запланирован"),
                            ("completed", "Проведён"),
                            ("cancelled", "Отменён"),
                        ],
                        db_index=True,
                        default="planned",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "cancellation_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Причина отмены"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="academy.group",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="academy.courselessonplan",
                        verbose_name="План занятия",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="users.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="academy.room",
                        verbose_name="Аудитория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Занятие",
                "verbose_name_plural": "Занятия",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="KPILesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_students",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего студентов"
                    ),
                ),
                (
                    "present_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Присутствовало"
                    ),
                ),
                (
                    "absent_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Отсутствовало"
                    ),
                ),
                (
                    "late_count",
                    models.PositiveIntegerField(default=0, verbose_name="Опозданий"),
                ),
                (
                    "attendance_percent",
                    models.FloatField(default=0, verbose_name="Посещаемость, %"),
                ),
                (
                    "total_homeworks",
                    models.PositiveIntegerField(default=0, verbose_name="Всего ДЗ"),
                ),
                (
                    "homework_completed_count",
                    models.PositiveIntegerField(default=0, verbose_name="Выполнено ДЗ"),
                ),
                (
                    "homework_completion_percent",
                    models.FloatField(default=0, verbose_name="Выполнение ДЗ, %"),
                ),
                (
                    "average_homework_score",
                    models.FloatField(default=0, verbose_name="Средний балл за ДЗ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi",
                        to="academy.lesson",
                        verbose_name="Занятие",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI занятия",
                "verbose_name_plural": "KPI занятий",
                "ordering": ["-lesson__date"],
            },
        ),
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="Срок сдачи"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homeworks",
                        to="academy.lesson",
                        verbose_name="Занятие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Домашнее задание",
                "verbose_name_plural": "Домашние задания",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Фамилия"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="Телефон"),
                ),
                (
                    "parent_phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Телефон родителя"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активен"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="academy.group",
                        verbose_name="Группа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Студент",
                "verbose_name_plural": "Студенты",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="KPIStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField(verbose_name="Период с")),
                ("date_to", models.DateField(verbose_name="Период по")),
                (
                    "total_lessons",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего занятий"
                    ),
                ),
                (
                    "present_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Присутствовал"
                    ),
                ),
                (
                    "absent_count",
                    models.PositiveIntegerField(default=0, verbose_name="Отсутствовал"),
                ),
                (
                    "late_count",
                    models.PositiveIntegerField(default=0, verbose_name="Опозданий"),
                ),
                (
                    "attendance_percent",
                    models.FloatField(default=0, verbose_name="Посещаемость, %"),
                ),
                (
                    "total_homeworks",
                    models.PositiveIntegerField(default=0, verbose_name="Всего ДЗ"),
                ),
                (
                    "completed_homeworks",
                    models.PositiveIntegerField(default=0, verbose_name="Выполнено ДЗ"),
                ),
                (
                    "missed_homeworks",
                    models.PositiveIntegerField(default=0, verbose_name="Пропущено ДЗ"),
                ),
                (
                    "homework_completion_percent",
                    models.FloatField(default=0, verbose_name="Выполнение ДЗ, %"),
                ),
                (
                    "average_score",
                    models.FloatField(default=0, verbose_name="Средний балл"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_kpi_records",
                        to="academy.group",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_records",
                        to="academy.student",
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI студента",
                "verbose_name_plural": "KPI студентов",
                "ordering": ["-date_to"],
            },
        ),
        migrations.CreateModel(
            name="HomeworkResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "Не сдано"),
                            ("submitted", "Сдано"),
                            ("checked", "Проверено"),
                            ("late", "Сдано с опозданием"),
                        ],
                        db_index=True,
                        default="not_submitted",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="От 0 до 10.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Баллы",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Комментарий"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата сдачи"
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата проверки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "homework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="academy.homework",
                        verbose_name="Домашнее задание",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_results",
                        to="academy.student",
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат домашнего задания",
                "verbose_name_plural": "Результаты домашних заданий",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Присутствовал"),
                            ("absent", "Отсутствовал"),
                            ("late", "Опоздал"),
                            ("excused", "Уважительная причина"),
                        ],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Комментарий"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="academy.lesson",
                        verbose_name="Занятие",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="academy.student",
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Посещаемость",
                "verbose_name_plural": "Посещаемость",
                "ordering": ["-lesson__date"],
            },
        ),
        migrations.AddConstraint(
            model_name="courselessonplan",
            constraint=models.UniqueConstraint(
                fields=("course", "lesson_number"), name="unique_course_lesson_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="kpiattendance",
            constraint=models.UniqueConstraint(
                fields=("group", "date_from", "date_to"),
                name="unique_kpi_attendance_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="kpigroup",
            constraint=models.UniqueConstraint(
                fields=("group", "date_from", "date_to"), name="unique_kpi_group_period"
            ),
        ),
        migrations.AddConstraint(
            model_name="kpihomework",
            constraint=models.UniqueConstraint(
                fields=("group", "date_from", "date_to"),
                name="unique_kpi_homework_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="kpiteacher",
            constraint=models.UniqueConstraint(
                fields=("teacher", "date_from", "date_to"),
                name="unique_kpi_teacher_period",
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["group", "date"], name="ix_lesson_group_date"),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["subject", "date"], name="ix_lesson_subject_date"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["status", "date"], name="ix_lesson_status_date"),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                fields=("group", "lesson_number"), name="unique_group_lesson_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="kpistudent",
            constraint=models.UniqueConstraint(
                fields=("student", "group", "date_from", "date_to"),
                name="unique_kpi_student_period",
            ),
        ),
        migrations.AddIndex(
            model_name="homeworkresult",
            index=models.Index(
                fields=["homework", "student"], name="ix_hwresult_hw_student"
            ),
        ),
        migrations.AddIndex(
            model_name="homeworkresult",
            index=models.Index(
                fields=["student", "status"], name="ix_hwresult_student_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="homeworkresult",
            constraint=models.UniqueConstraint(
                fields=("homework", "student"), name="unique_homework_student_result"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["student", "lesson"], name="ix_attendance_student_lesson"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["lesson", "status"], name="ix_attendance_lesson_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("student", "lesson"), name="unique_student_lesson_attendance"
            ),
        ),
    ]
