# Generated by Django 6.1 on 2026-09-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="kpiattendance",
            name="unique_kpi_attendance_period",
        ),
        migrations.RemoveConstraint(
            model_name="kpigroup",
            name="unique_kpi_group_period",
        ),
        migrations.RemoveConstraint(
            model_name="kpihomework",
            name="unique_kpi_homework_period",
        ),
        migrations.RemoveField(
            model_name="kpilesson",
            name="lesson",
        ),
        migrations.RemoveConstraint(
            model_name="kpistudent",
            name="unique_kpi_student_period",
        ),
        migrations.RemoveConstraint(
            model_name="kpiteacher",
            name="unique_kpi_teacher_period",
        ),
        migrations.RemoveField(
            model_name="kpiattendance",
            name="group",
        ),
        migrations.RemoveField(
            model_name="kpigroup",
            name="group",
        ),
        migrations.RemoveField(
            model_name="kpihomework",
            name="group",
        ),
        migrations.DeleteModel(
            name="KPILesson",
        ),
        migrations.RemoveField(
            model_name="kpistudent",
            name="group",
        ),
        migrations.RemoveField(
            model_name="kpistudent",
            name="student",
        ),
        migrations.RemoveField(
            model_name="kpiteacher",
            name="teacher",
        ),
        migrations.DeleteModel(
            name="KPIAttendance",
        ),
        migrations.DeleteModel(
            name="KPIGroup",
        ),
        migrations.DeleteModel(
            name="KPIHomework",
        ),
        migrations.DeleteModel(
            name="KPIStudent",
        ),
        migrations.DeleteModel(
            name="KPITeacher",
        ),
    ]
