# Generated by Django 6.1 on 2026-09-10 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0002_remove_kpiattendance_unique_kpi_attendance_period_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Тренер, который ведёт именно это занятие. Заполняется генератором из расписания группы; для занятий, созданных до появления нескольких тренеров на группу, может быть пустым — тогда тренером считается group.teacher (см. apps.academy.permissions).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="users.teacher",
                verbose_name="Тренер",
            ),
        ),
        migrations.CreateModel(
            name="GroupSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("mon", "Понедельник"),
                            ("tue", "Вторник"),
                            ("wed", "Среда"),
                            ("thu", "Четверг"),
                            ("fri", "Пятница"),
                            ("sat", "Суббота"),
                            ("sun", "Воскресенье"),
                        ],
                        db_index=True,
                        max_length=3,
                        verbose_name="День недели",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Время начала")),
                ("end_time", models.TimeField(verbose_name="Время окончания")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Неактивные слоты игнорируются при генерации занятий и проверке конфликтов.",
                        verbose_name="Активно",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="academy.group",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="group_schedules",
                        to="academy.room",
                        verbose_name="Аудитория",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        help_text="Предмет этого слота. Пусто — унаследованный слот без явного предмета (для него занятия создаются по общему порядку плана курса).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_schedules",
                        to="users.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_schedules",
                        to="users.teacher",
                        verbose_name="Тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слот расписания группы",
                "verbose_name_plural": "Расписание группы",
                "ordering": ["group", "day_of_week", "start_time"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                help_text="Слот GroupSchedule, из которого сгенерировано это занятие (если есть).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="academy.groupschedule",
                verbose_name="Слот расписания",
            ),
        ),
        migrations.AddIndex(
            model_name="groupschedule",
            index=models.Index(
                fields=["group", "day_of_week"], name="ix_gsched_group_day"
            ),
        ),
        migrations.AddIndex(
            model_name="groupschedule",
            index=models.Index(
                fields=["teacher", "day_of_week"], name="ix_gsched_teacher_day"
            ),
        ),
        migrations.AddIndex(
            model_name="groupschedule",
            index=models.Index(
                fields=["room", "day_of_week"], name="ix_gsched_room_day"
            ),
        ),
    ]
