# Generated by Django 6.1 on 2026-09-11 03:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0004_backfill_group_schedule"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Неактивные назначения игнорируются при генерации занятий и проверке конфликтов.",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "is_legacy_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Автоматически синхронизируется с Group.teacher — не редактируется вручную.",
                        verbose_name="Основной тренер группы",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Тренер группы",
                "verbose_name_plural": "Тренеры группы",
                "ordering": ["group", "id"],
            },
        ),
        migrations.CreateModel(
            name="GroupTeacherLessonPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lesson_number",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Номер занятия",
                    ),
                ),
                ("topic", models.CharField(max_length=255, verbose_name="Тема")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "youtube_url",
                    models.URLField(blank=True, verbose_name="Ссылка на YouTube"),
                ),
                (
                    "presentation_urls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Список URL.",
                        verbose_name="Ссылки на презентации",
                    ),
                ),
                (
                    "homework_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Название домашнего задания",
                    ),
                ),
                (
                    "homework_description",
                    models.TextField(
                        blank=True, verbose_name="Описание домашнего задания"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "План занятия тренера",
                "verbose_name_plural": "Планы занятий тренеров",
                "ordering": ["group_teacher", "lesson_number"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="lesson",
            name="unique_group_lesson_number",
        ),
        migrations.AddField(
            model_name="groupteacher",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teachers",
                to="academy.group",
                verbose_name="Группа",
            ),
        ),
        migrations.AddField(
            model_name="groupteacher",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                help_text="Предмет, который этот тренер ведёт в этой группе. Пусто — автоматически синхронизированный основной тренер группы (Group.teacher), без единого фиксированного предмета.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="group_assignments",
                to="users.subject",
                verbose_name="Предмет",
            ),
        ),
        migrations.AddField(
            model_name="groupteacher",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="group_assignments",
                to="users.teacher",
                verbose_name="Тренер",
            ),
        ),
        migrations.AddField(
            model_name="groupschedule",
            name="group_teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Заполняется автоматически из group/teacher/subject при сохранении.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="academy.groupteacher",
                verbose_name="Тренер группы",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="group_teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Тренер группы (GroupTeacher), которому принадлежит это занятие и его нумерация. Заполняется автоматически при сохранении, если не указано явно.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="academy.groupteacher",
                verbose_name="Тренер группы",
            ),
        ),
        migrations.AddField(
            model_name="groupteacherlessonplan",
            name="group_teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_plans",
                to="academy.groupteacher",
                verbose_name="Тренер группы",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="individual_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Заполняется вместо `plan`, когда тренер использует свой собственный план (GroupTeacherLessonPlan).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="academy.groupteacherlessonplan",
                verbose_name="Индивидуальный план занятия",
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["group_teacher", "lesson_number"],
                name="ix_lesson_gteacher_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                fields=("group_teacher", "lesson_number"),
                name="unique_group_teacher_lesson_number",
            ),
        ),
        migrations.AddIndex(
            model_name="groupteacher",
            index=models.Index(
                fields=["group", "is_active"], name="ix_gteacher_group_active"
            ),
        ),
        migrations.AddIndex(
            model_name="groupteacher",
            index=models.Index(fields=["teacher"], name="ix_gteacher_teacher"),
        ),
        migrations.AddConstraint(
            model_name="groupteacher",
            constraint=models.UniqueConstraint(
                fields=("group", "teacher", "subject"),
                name="unique_group_teacher_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupteacherlessonplan",
            constraint=models.UniqueConstraint(
                fields=("group_teacher", "lesson_number"),
                name="unique_group_teacher_lesson_number_plan",
            ),
        ),
    ]
