# Generated by Django 6.1 on 2026-09-11 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0006_backfill_group_teacher"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="days_of_week",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Устаревшее поле, например: ['mon', 'wed', 'fri'] — см. help_text поля «Тренер (устар.)».",
                verbose_name="Дни недели (устар.)",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="end_time",
            field=models.TimeField(
                blank=True,
                help_text="Устаревшее поле — см. help_text поля «Тренер (устар.)».",
                null=True,
                verbose_name="Время окончания (устар.)",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="room",
            field=models.ForeignKey(
                blank=True,
                help_text="Устаревшее поле — см. help_text поля «Тренер (устар.)».",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="academy.room",
                verbose_name="Аудитория (устар.)",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="start_time",
            field=models.TimeField(
                blank=True,
                help_text="Устаревшее поле — см. help_text поля «Тренер (устар.)».",
                null=True,
                verbose_name="Время начала (устар.)",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Устаревшее поле, оставлено только для совместимости со старыми данными. Тренеров группы назначайте через «Тренеры / программы» (GroupTeacher) — это поле больше не влияет на расписание и генерацию занятий.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="groups",
                to="users.teacher",
                verbose_name="Тренер (устар.)",
            ),
        ),
        migrations.AlterField(
            model_name="groupteacher",
            name="is_legacy_primary",
            field=models.BooleanField(
                default=False,
                help_text="Чисто историческая метка: эта программа была создана переносом старых Group.teacher/room/start_time/end_time/days_of_week, а не добавлена вручную. Не даёт этой программе никаких особых прав или поведения — она полностью равноправна любой другой Teacher Program этой группы.",
                verbose_name="Перенесено из устаревших полей группы",
            ),
        ),
        migrations.AlterField(
            model_name="groupteacher",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                help_text="Предмет, который этот тренер ведёт в этой группе. Пусто — обычно означает программу, перенесённую из устаревших полей Group (teacher/room/schedule), без единого фиксированного предмета; это не влияет на то, как эта программа обрабатывается.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="group_assignments",
                to="users.subject",
                verbose_name="Предмет",
            ),
        ),
    ]
