# Generated by Django 6.1 on 2026-09-11 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_final_legacy_schedule_sync'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list, help_text='Устаревшее поле, не используется — см. help_text поля «Тренер (устар.)».', verbose_name='Дни недели (устар.)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Устаревшее поле, не используется — см. help_text поля «Тренер (устар.)».', null=True, verbose_name='Время окончания (устар.)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Устаревшее поле, не используется — см. help_text поля «Тренер (устар.)».', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='academy.room', verbose_name='Аудитория (устар.)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Устаревшее поле, не используется — см. help_text поля «Тренер (устар.)».', null=True, verbose_name='Время начала (устар.)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Устаревшее поле, оставлено только для совместимости со старыми данными. Не отображается в админке или API и не используется генерацией занятий, расписанием, аналитикой или правами доступа — источник истины: GroupTeacher/GroupSchedule.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='users.teacher', verbose_name='Тренер (устар.)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Тренер, который ведёт именно это занятие. Заполняется генератором из расписания группы; может быть пустым — тогда тренером считается тренер из group_teacher (см. Lesson.effective_teacher).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='users.teacher', verbose_name='Тренер'),
        ),
    ]
