# Generated by Django 5.2.17 on 2026-09-12 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0009_alter_group_days_of_week_alter_group_end_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courselessonplan",
            options={
                "ordering": ["course", "lesson_number"],
                "verbose_name": "План занятия курса",
                "verbose_name_plural": "Планы занятий",
            },
        ),
        migrations.AlterModelOptions(
            name="groupteacher",
            options={
                "ordering": ["group", "id"],
                "verbose_name": "Учебная программа",
                "verbose_name_plural": "Учебные программы",
            },
        ),
        migrations.AlterModelOptions(
            name="groupteacherlessonplan",
            options={
                "ordering": ["group_teacher", "lesson_number"],
                "verbose_name": "План занятий программы",
                "verbose_name_plural": "Планы занятий программ",
            },
        ),
        migrations.AlterField(
            model_name="groupschedule",
            name="group_teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Заполняется автоматически из group/teacher/subject при сохранении.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="academy.groupteacher",
                verbose_name="Учебная программа",
            ),
        ),
        migrations.AlterField(
            model_name="groupteacherlessonplan",
            name="group_teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_plans",
                to="academy.groupteacher",
                verbose_name="Учебная программа",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="group_teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Тренер группы (GroupTeacher), которому принадлежит это занятие и его нумерация. Заполняется автоматически при сохранении, если не указано явно.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="academy.groupteacher",
                verbose_name="Учебная программа",
            ),
        ),
    ]
