# Generated by Django 6.1 on 2026-09-14 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _rename_planned_to_scheduled(apps, schema_editor):
    """Existing rows stored the old `Lesson.Status.PLANNED` value
    ("planned") — the enum member is renamed to SCHEDULED ("scheduled") as
    part of introducing the full scheduled/in_progress/completed/cancelled
    lifecycle (see models.Lesson.Status). Every other status value is
    unaffected."""
    Lesson = apps.get_model("academy", "Lesson")
    Lesson.objects.filter(status="planned").update(status="scheduled")


def _rename_scheduled_to_planned(apps, schema_editor):
    Lesson = apps.get_model("academy", "Lesson")
    Lesson.objects.filter(status="scheduled").update(status="planned")


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0009_alter_group_days_of_week_alter_group_end_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Завершено"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_lessons",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Завершил",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="homework_not_required",
            field=models.BooleanField(
                default=False,
                help_text="Явно отмечено тренером/администратором как занятие без домашнего задания — снимает требование иметь Homework для завершения занятия.",
                verbose_name="ДЗ не требуется",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Начато"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Запланирован"),
                    ("in_progress", "Идёт занятие"),
                    ("completed", "Проведён"),
                    ("cancelled", "Отменён"),
                ],
                db_index=True,
                default="scheduled",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.RunPython(_rename_planned_to_scheduled, _rename_scheduled_to_planned),
    ]
