# Generated by Django 5.2.17 on 2026-09-19 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0011_monthlyteacherreport"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="monthlyteacherreport",
            options={
                "ordering": ["-year", "-month"],
                "verbose_name": "Отчёт преподавателя",
                "verbose_name_plural": "Отчёты преподавателей",
            },
        ),
        migrations.AlterField(
            model_name="monthlyteacherreport",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Комментарий преподавателя о проделанной работе за месяц.",
                verbose_name="Итог месяца",
            ),
        ),
        migrations.AlterField(
            model_name="monthlyteacherreport",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_reports",
                to="users.teacher",
                verbose_name="Преподаватель",
            ),
        ),
    ]
