# Generated by Django 6.1 on 2026-09-20 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0013_academymonthlyreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentStatusEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("deactivated", "Деактивация"),
                            ("reactivated", "Повторная активация"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Тип события",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no_interest", "Нет интереса"),
                            ("disliked_teacher", "Не понравился преподаватель"),
                            ("family_circumstances", "Семейные обстоятельства"),
                            ("will_continue_later", "Продолжим через некоторое время"),
                            ("financial_issues", "Финансовые проблемы"),
                            ("not_enough_time", "Не хватает времени / другие курсы"),
                            ("relocation", "Переезд"),
                            ("health", "Состояние здоровья"),
                            ("changed_plans", "Изменение планов"),
                            ("other", "Другая причина"),
                        ],
                        db_index=True,
                        help_text="Заполняется только для деактивации.",
                        max_length=30,
                        verbose_name="Причина",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "event_date",
                    models.DateField(
                        help_text="Для деактивации — дата ухода (сегодня). Для возврата — выбранная дата возвращения.",
                        verbose_name="Дата события",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Группа студента на момент события (уход — прежняя группа, возврат — новая группа).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_status_events",
                        to="academy.group",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_status_events_performed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто оформил",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_events",
                        to="academy.student",
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие статуса студента",
                "verbose_name_plural": "События статуса студентов",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "-created_at"],
                        name="ix_stustatus_student_created",
                    ),
                    models.Index(
                        fields=["event_type", "event_date"],
                        name="ix_stustatus_type_date",
                    ),
                ],
            },
        ),
    ]
