# Generated by Django 6.1 on 2026-09-20 07:37

from django.db import migrations, models


def backfill_status_from_is_active(apps, schema_editor):
    """Existing rows predate the `status` field — the only fact we already
    know about them is `is_active`, so every currently-inactive Student is
    backfilled as "withdrawn" (the only inactive status that existed before
    this migration; PAUSED/COMPLETED are new states that could not have
    produced any existing data) and every active one as "active"."""
    Student = apps.get_model("academy", "Student")
    Student.objects.filter(is_active=True).update(status="active")
    Student.objects.filter(is_active=False).update(status="withdrawn")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0014_studentstatusevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Активен"),
                    ("paused", "На паузе"),
                    ("completed", "Завершил обучение"),
                    ("withdrawn", "Деактивирован"),
                ],
                db_index=True,
                default="active",
                help_text="Управляется действиями «Деактивировать» / «Приостановить» / «Завершить обучение» / «Продолжить обучение» / «Активировать» — не редактируется напрямую.",
                max_length=20,
                verbose_name="Статус обучения",
            ),
        ),
        migrations.AddField(
            model_name="studentstatusevent",
            name="expected_return_date",
            field=models.DateField(
                blank=True,
                help_text="Только для приостановки обучения — предполагаемая дата, когда студент вернётся.",
                null=True,
                verbose_name="Ожидаемая дата возвращения",
            ),
        ),
        migrations.AddField(
            model_name="studentstatusevent",
            name="previous_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Активен"),
                    ("paused", "На паузе"),
                    ("completed", "Завершил обучение"),
                    ("withdrawn", "Деактивирован"),
                ],
                help_text="Снимок Student.status непосредственно перед этим событием — источник для различения, например, «вернулся после паузы» (previous_status=paused) от «повторно активирован после ухода» (previous_status=withdrawn).",
                max_length=20,
                verbose_name="Статус до события",
            ),
        ),
        migrations.AddField(
            model_name="studentstatusevent",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата обновления записи"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Производное от «Статус обучения» — True только при статусе «Активен». Меняется исключительно через services.student_status, никогда напрямую.",
                verbose_name="Активен",
            ),
        ),
        migrations.AlterField(
            model_name="studentstatusevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("deactivated", "Деактивация"),
                    ("reactivated", "Повторная активация"),
                    ("completed", "Завершение обучения"),
                    ("paused", "Приостановка обучения"),
                    ("continued", "Продолжение обучения"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Тип события",
            ),
        ),
        migrations.AlterField(
            model_name="studentstatusevent",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_interest", "Нет интереса"),
                    ("disliked_teacher", "Не понравился преподаватель"),
                    ("family_circumstances", "Семейные обстоятельства"),
                    ("will_continue_later", "Продолжим через некоторое время"),
                    ("financial_issues", "Финансовые проблемы"),
                    ("not_enough_time", "Не хватает времени / другие курсы"),
                    ("relocation", "Переезд"),
                    ("health", "Состояние здоровья"),
                    ("changed_plans", "Изменение планов"),
                    ("other", "Другая причина"),
                ],
                db_index=True,
                help_text="Заполняется для деактивации и приостановки обучения.",
                max_length=30,
                verbose_name="Причина",
            ),
        ),
        migrations.RunPython(backfill_status_from_is_active, noop_reverse),
    ]
