# Generated by Django 6.1 on 2026-09-23 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0015_student_education_status"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lesson",
            name="unique_group_teacher_lesson_number",
        ),
        migrations.AddField(
            model_name="lesson",
            name="rescheduled_from",
            field=models.OneToOneField(
                blank=True,
                help_text="Отменённое занятие, тема которого перенесена на это занятие (см. services.lesson_reschedule). У одного отменённого занятия может быть только один перенос — это же защищает от повторного запуска переноса.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rescheduled_to",
                to="academy.lesson",
                verbose_name="Перенос отменённого занятия",
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "cancelled"), _negated=True),
                fields=("group_teacher", "lesson_number"),
                name="unique_active_group_teacher_lesson_number",
            ),
        ),
    ]
