# Generated by Django 6.1 on 2026-10-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0017_student_enrollment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="manually_edited",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Тренер или администратор вручную изменил содержание занятия (тему, описание, материалы) или его домашнее задание. «Сгенерировать занятия» не перезаписывает такое занятие данными плана.",
                verbose_name="Изменено вручную",
            ),
        ),
    ]
