# Generated by Django 6.1 on 2026-10-05 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0019_lesson_schedule_overridden"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentstatusevent",
            name="from_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Только для перевода — группа, из которой студента перевели (в «Группа» — новая).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_transfers_out",
                to="academy.group",
                verbose_name="Из группы",
            ),
        ),
        migrations.AlterField(
            model_name="studentstatusevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("deactivated", "Деактивация"),
                    ("reactivated", "Повторная активация"),
                    ("completed", "Завершение обучения"),
                    ("paused", "Приостановка обучения"),
                    ("continued", "Продолжение обучения"),
                    ("transferred", "Перевод в другую группу"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Тип события",
            ),
        ),
    ]
