# Generated by Django 6.1 on 2026-10-09 07:37

from django.db import migrations, models
from django.db.models import Max


def backfill_departures(apps, schema_editor):
    """Fill the new snapshots of past departures from the records that
    exist — never a guessed value; a reason left blank stays blank
    («Не указана» in reports)."""
    Event = apps.get_model("academy", "StudentStatusEvent")
    Attendance = apps.get_model("academy", "Attendance")
    HomeworkResult = apps.get_model("academy", "HomeworkResult")
    events = Event.objects.filter(event_type__in=("deactivated", "completed")).select_related("student")
    for event in events.iterator():
        attended = (
            Attendance.objects.filter(student_id=event.student_id, status__in=("present", "late"),
                                      lesson__date__lte=event.event_date)
            .exclude(lesson__status="cancelled").aggregate(d=Max("lesson__date"))["d"]
        )
        submitted = (
            HomeworkResult.objects.filter(student_id=event.student_id, status__in=("submitted", "checked", "late"),
                                          submitted_at__date__lte=event.event_date)
            .aggregate(d=Max("submitted_at__date"))["d"]
        )
        start = event.student.enrollment_date
        event.last_activity_date = max((d for d in (attended, submitted) if d is not None), default=None)
        event.study_days = (event.event_date - start).days if start and start <= event.event_date else None
        event.save(update_fields=["last_activity_date", "study_days"])


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0020_studentstatusevent_transfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentstatusevent",
            name="last_activity_date",
            field=models.DateField(
                blank=True,
                help_text="Последнее посещение (был / опоздал) или сданное ДЗ на дату события; пусто — активности не было.",
                null=True,
                verbose_name="Последняя активность до ухода",
            ),
        ),
        migrations.AddField(
            model_name="studentstatusevent",
            name="study_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="От даты начала обучения до даты события.",
                null=True,
                verbose_name="Срок обучения до ухода (дней)",
            ),
        ),
        migrations.AlterField(
            model_name="studentstatusevent",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("financial_issues", "Финансовые трудности"),
                    ("transport", "Неудобный адрес или транспорт"),
                    ("schedule", "Неудобное расписание"),
                    ("disliked_classes", "Не понравились занятия"),
                    ("disliked_teacher", "Не понравился тренер"),
                    ("no_interest", "Потеря интереса"),
                    ("low_motivation", "Низкая мотивация и частые пропуски"),
                    ("other_academy", "Переход в другую академию"),
                    ("relocation", "Переезд"),
                    ("graduated", "Завершение обучения"),
                    ("other", "Другая причина"),
                    ("family_circumstances", "Семейные обстоятельства"),
                    ("will_continue_later", "Продолжим через некоторое время"),
                    ("not_enough_time", "Не хватает времени / другие курсы"),
                    ("health", "Состояние здоровья"),
                    ("changed_plans", "Изменение планов"),
                ],
                db_index=True,
                help_text="Заполняется для деактивации и приостановки обучения.",
                max_length=30,
                verbose_name="Причина",
            ),
        ),
        migrations.RunPython(backfill_departures, migrations.RunPython.noop),
    ]
