# Generated by Django 6.1 on 2026-10-09 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0021_student_departure_history"),
        ("users", "0004_teacher_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainerAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(db_index=True, verbose_name="Отвечает с"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Первый день, когда тренер уже не отвечает за программу (не включительно). Пусто — отвечает сейчас.",
                        null=True,
                        verbose_name="Не отвечает с",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="assignment",
                        help_text="assignment — назначение в LMS; migration — восстановлено из существующих данных при переходе на историю.",
                        max_length=20,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Записано"),
                ),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Закрыто"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто назначил",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_assignments",
                        to="academy.group",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="academy.groupteacher",
                        verbose_name="Программа (тренер группы)",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trainer_assignments",
                        to="users.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trainer_assignments",
                        to="users.teacher",
                        verbose_name="Тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Назначение тренера",
                "verbose_name_plural": "История назначений тренеров",
                "ordering": ["group", "program", "start_date", "id"],
                "indexes": [
                    models.Index(
                        fields=["teacher", "start_date"],
                        name="ix_tassign_teacher_start",
                    ),
                    models.Index(
                        fields=["program", "start_date"],
                        name="ix_tassign_program_start",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("end_date__isnull", True)),
                        fields=("program",),
                        name="unique_open_trainer_assignment",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_date__isnull", True),
                            ("end_date__gte", models.F("start_date")),
                            _connector="OR",
                        ),
                        name="trainer_assignment_end_after_start",
                    ),
                ],
            },
        ),
    ]
