# Generated by Django 6.1 on 2026-09-25 02:59

import apps.feedback.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academy", "0016_lesson_reschedule"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="Вариант")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответа",
                "ordering": ["question", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SurveyAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_value", models.TextField(blank=True, max_length=5000)),
            ],
            options={
                "verbose_name": "Ответ на вопрос",
                "verbose_name_plural": "Ответы на вопросы",
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Показывается респонденту над вопросами.",
                        max_length=2000,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[("parent", "Родители"), ("student", "Студенты")],
                        db_index=True,
                        default="parent",
                        max_length=20,
                        verbose_name="Аудитория",
                    ),
                ),
                (
                    "visibility_mode",
                    models.CharField(
                        choices=[
                            ("open", "Открытый отзыв"),
                            ("anonymous", "Анонимный отзыв"),
                            ("both", "На выбор респондента"),
                        ],
                        default="anonymous",
                        help_text="Открытый — респондент указывает имя, администратор его видит. Анонимный — имя не спрашивается и не сохраняется. На выбор — респондент сам решает при заполнении.",
                        max_length=20,
                        verbose_name="Тип отзыва",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("published", "Опубликован"),
                            ("closed", "Закрыт"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Начало приёма ответов"
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Окончание приёма ответов"
                    ),
                ),
                (
                    "max_responses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Пусто — без ограничения.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100000),
                        ],
                        verbose_name="Максимум ответов",
                    ),
                ),
                (
                    "allow_multiple_submissions",
                    models.BooleanField(
                        default=False,
                        help_text="Выключено — после отправки браузер запоминает, что ответ уже дан. Это защита от случайных повторов, а не проверка личности.",
                        verbose_name="Разрешить повторные ответы",
                    ),
                ),
                (
                    "child_name_mode",
                    models.CharField(
                        choices=[
                            ("required", "Обязательно"),
                            ("optional", "Необязательно"),
                            ("not_collected", "Не спрашивать"),
                        ],
                        default="optional",
                        help_text="Только для опросов родителей. Имя ребёнка не проверяется — это данные со слов родителя.",
                        max_length=20,
                        verbose_name="Имя ребёнка",
                    ),
                ),
                (
                    "ask_child_name_when_anonymous",
                    models.BooleanField(
                        default=False,
                        help_text="Имя ребёнка косвенно указывает на родителя — такой ответ уже не полностью анонимный, и форма предупредит об этом респондента.",
                        verbose_name="Спрашивать имя ребёнка в анонимном отзыве",
                    ),
                ),
                (
                    "confirmation_message",
                    models.TextField(
                        blank=True,
                        default="Спасибо! Ваш ответ отправлен.",
                        max_length=1000,
                        verbose_name="Сообщение после отправки",
                    ),
                ),
                (
                    "public_token",
                    models.CharField(
                        default=apps.feedback.models.generate_public_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="Токен ссылки",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Опубликован",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="Закрыт"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_surveys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_surveys",
                        to="academy.group",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_surveys",
                        to="users.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_surveys",
                        to="users.teacher",
                        verbose_name="Тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опрос",
                "verbose_name_plural": "Опросы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SurveyAnswerOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_links",
                        to="feedback.surveyanswer",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answer_links",
                        to="feedback.questionoption",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="surveyanswer",
            name="selected_options",
            field=models.ManyToManyField(
                blank=True,
                related_name="answers",
                through="feedback.SurveyAnswerOption",
                to="feedback.questionoption",
            ),
        ),
        migrations.CreateModel(
            name="SurveyQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="Вопрос")),
                (
                    "help_text",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Подсказка"
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("text", "Текстовый ответ"),
                            ("single_choice", "Один вариант"),
                            ("multiple_choice", "Несколько вариантов"),
                        ],
                        default="single_choice",
                        max_length=20,
                        verbose_name="Тип вопроса",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="Обязательный"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "is_multiline",
                    models.BooleanField(
                        default=True, verbose_name="Многострочный ответ"
                    ),
                ),
                (
                    "min_length",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(5000)],
                        verbose_name="Мин. длина",
                    ),
                ),
                (
                    "max_length",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5000),
                        ],
                        verbose_name="Макс. длина",
                    ),
                ),
                (
                    "min_selections",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(30)],
                        verbose_name="Мин. выбранных",
                    ),
                ),
                (
                    "max_selections",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="Макс. выбранных",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="feedback.survey",
                        verbose_name="Опрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос опроса",
                "verbose_name_plural": "Вопросы опроса",
                "ordering": ["survey", "order", "id"],
            },
        ),
        migrations.AddField(
            model_name="surveyanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="answers",
                to="feedback.surveyquestion",
            ),
        ),
        migrations.AddField(
            model_name="questionoption",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="feedback.surveyquestion",
                verbose_name="Вопрос",
            ),
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("open", "Открытый"), ("anonymous", "Анонимный")],
                        db_index=True,
                        max_length=20,
                        verbose_name="Тип отзыва",
                    ),
                ),
                (
                    "respondent_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Имя респондента"
                    ),
                ),
                (
                    "child_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Имя ребёнка (со слов)"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Отправлено",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="feedback.survey",
                        verbose_name="Опрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ на опрос",
                "verbose_name_plural": "Ответы на опросы",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddField(
            model_name="surveyanswer",
            name="response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="feedback.surveyresponse",
            ),
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(
                fields=["audience", "status"], name="ix_survey_audience_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="survey",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("starts_at__isnull", True),
                    ("ends_at__isnull", True),
                    ("ends_at__gt", models.F("starts_at")),
                    _connector="OR",
                ),
                name="survey_ends_after_starts",
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyansweroption",
            constraint=models.UniqueConstraint(
                fields=("answer", "option"), name="unique_answer_option"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyquestion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("min_length__isnull", True),
                    ("max_length__isnull", True),
                    ("max_length__gte", models.F("min_length")),
                    _connector="OR",
                ),
                name="question_length_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyquestion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("min_selections__isnull", True),
                    ("max_selections__isnull", True),
                    ("max_selections__gte", models.F("min_selections")),
                    _connector="OR",
                ),
                name="question_selection_range_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(
                fields=["survey", "submitted_at"], name="ix_response_survey_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyresponse",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("visibility", "anonymous"), _negated=True),
                    ("respondent_name", ""),
                    _connector="OR",
                ),
                name="anonymous_response_has_no_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyanswer",
            constraint=models.UniqueConstraint(
                fields=("response", "question"), name="unique_answer_per_question"
            ),
        ),
    ]
