# Generated by Django 6.1 on 2026-10-04 08:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academy", "0018_lesson_manually_edited"),
        ("users", "0002_user_role_team_lead"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamLeadReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("daily", "Ежедневный отчёт"),
                            ("weekly", "Еженедельный отчёт"),
                            ("meeting", "Встреча с командой"),
                            ("lesson_visit", "Посещение занятия"),
                            ("trainer_review", "Отчёт по тренеру"),
                            ("problem_student", "Проблемный студент"),
                            ("internship", "Стажировка нового тренера"),
                            ("probation", "Испытательный срок"),
                            ("monthly", "Ежемесячный отчёт"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Вид отчёта",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        verbose_name="Дата",
                    ),
                ),
                (
                    "period_start",
                    models.DateField(blank=True, null=True, verbose_name="Период с"),
                ),
                (
                    "period_end",
                    models.DateField(blank=True, null=True, verbose_name="Период по"),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Данные отчёта"
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Показатели LMS"
                    ),
                ),
                (
                    "metrics_calculated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Показатели посчитаны"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teamlead_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teamlead_reports",
                        to="academy.group",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teamlead_reports",
                        to="academy.lesson",
                        verbose_name="Занятие",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teamlead_reports",
                        to="academy.student",
                        verbose_name="Студент",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teamlead_reports",
                        to="users.teacher",
                        verbose_name="Тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчёт Team Lead",
                "verbose_name_plural": "Отчёты Team Lead",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="WorkLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_kind",
                    models.CharField(
                        choices=[("log", "Запись журнала"), ("task", "Задача")],
                        db_index=True,
                        default="log",
                        max_length=8,
                        verbose_name="Вид",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        verbose_name="Дата",
                    ),
                ),
                (
                    "time_from",
                    models.TimeField(blank=True, null=True, verbose_name="Время с"),
                ),
                (
                    "time_to",
                    models.TimeField(blank=True, null=True, verbose_name="Время до"),
                ),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("lesson_control", "Контроль занятия"),
                            ("trainer", "Работа с тренером"),
                            ("student", "Работа со студентом"),
                            ("exam", "Экзамен"),
                            ("hackathon", "Хакатон"),
                            ("meeting", "Собрание"),
                            ("internship", "Стажировка"),
                            ("probation", "Испытательный срок"),
                            ("analytics", "Аналитика"),
                            ("problem", "Проблема"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Тип работы",
                    ),
                ),
                (
                    "with_whom",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="С кем (если не группа/тренер/студент)",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="Задача"),
                ),
                ("goal", models.TextField(blank=True, verbose_name="Цель")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Что сделано"),
                ),
                ("result", models.TextField(blank=True, verbose_name="Результат")),
                (
                    "problem",
                    models.TextField(blank=True, verbose_name="Выявленная проблема"),
                ),
                (
                    "decision",
                    models.TextField(blank=True, verbose_name="Принятое решение"),
                ),
                (
                    "next_action",
                    models.TextField(blank=True, verbose_name="Следующее действие"),
                ),
                (
                    "responsible",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ответственный"
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="Срок"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Низкий"),
                            ("medium", "Средний"),
                            ("high", "Высокий"),
                            ("critical", "Критический"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_progress", "В работе"),
                            ("done", "Выполнено"),
                            ("overdue", "Просрочено"),
                            ("postponed", "Отложено"),
                            ("escalated", "Эскалировано"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="worklog_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worklog_entries",
                        to="academy.group",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="worklog.teamleadreport",
                        verbose_name="Отчёт",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worklog_entries",
                        to="academy.student",
                        verbose_name="Студент",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worklog_entries",
                        to="users.teacher",
                        verbose_name="Тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись рабочего журнала",
                "verbose_name_plural": "Рабочий журнал",
                "ordering": ["-date", "-time_from", "-id"],
            },
        ),
    ]
