# Generated by Django 6.1 on 2026-10-04 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Экзаменге даярдан",
                        max_length=120,
                        verbose_name="Заголовок главной",
                    ),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        default="Билимиңди текшер, машыгып көр жана экзаменге ишенимдүү даярдан.",
                        max_length=300,
                        verbose_name="Подзаголовок главной",
                    ),
                ),
                (
                    "start_button_label",
                    models.CharField(
                        default="Тренировка баштоо",
                        max_length=60,
                        verbose_name="Текст кнопки тренировки",
                    ),
                ),
                (
                    "exam_button_label",
                    models.CharField(
                        default="Экзаменге өтүү",
                        max_length=60,
                        verbose_name="Текст кнопки экзамена",
                    ),
                ),
                (
                    "exam_url",
                    models.URLField(
                        blank=True,
                        help_text="Куда ведёт кнопка «Экзаменге өтүү» (например, кабинет студента LMS). Пусто — кнопка скрыта.",
                        max_length=500,
                        validators=[
                            django.core.validators.URLValidator(
                                message="Укажите ссылку, начинающуюся с http:// или https://.",
                                schemes=["http", "https"],
                            )
                        ],
                        verbose_name="Ссылка на настоящий экзамен",
                    ),
                ),
                (
                    "exam_open_in_new_tab",
                    models.BooleanField(
                        default=False, verbose_name="Открывать экзамен в новой вкладке"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Настройки портала",
                "verbose_name_plural": "Настройки портала",
            },
        ),
        migrations.CreateModel(
            name="TrainingLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "url",
                    models.URLField(
                        max_length=500,
                        validators=[
                            django.core.validators.URLValidator(
                                message="Укажите ссылку, начинающуюся с http:// или https://.",
                                schemes=["http", "https"],
                            )
                        ],
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Категория"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Имя из Bootstrap Icons (icons.getbootstrap.com) без «bi-»: filetype-py, book, link-45deg…",
                        max_length=40,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z0-9-]{1,40}$",
                                "Имя иконки Bootstrap Icons без «bi-», например: filetype-py.",
                            )
                        ],
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "published",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Полезная ссылка",
                "verbose_name_plural": "Полезные ссылки",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TrainingVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "video_url",
                    models.URLField(
                        help_text="YouTube, Vimeo или прямая ссылка на видеофайл (.mp4/.webm). Файл на сервер не загружается.",
                        max_length=500,
                        validators=[
                            django.core.validators.URLValidator(
                                message="Укажите ссылку, начинающуюся с http:// или https://.",
                                schemes=["http", "https"],
                            )
                        ],
                        verbose_name="Ссылка на видео",
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True,
                        help_text="Необязательно: для YouTube обложка подставляется автоматически.",
                        max_length=500,
                        validators=[
                            django.core.validators.URLValidator(
                                message="Укажите ссылку, начинающуюся с http:// или https://.",
                                schemes=["http", "https"],
                            )
                        ],
                        verbose_name="Обложка (URL)",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Категория"
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        help_text="Например: 12:30.",
                        max_length=16,
                        verbose_name="Длительность",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "published",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Видео",
                "verbose_name_plural": "Видео",
                "ordering": ["order", "id"],
            },
        ),
    ]
