# Generated by Django 6.1 on 2026-10-04 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0010_trainer_security_fields"),
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trainer",
            fields=[],
            options={
                "verbose_name": "Тренажёр",
                "verbose_name_plural": "Тренажёры",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("testing.testsession",),
        ),
        migrations.AddField(
            model_name="portalsettings",
            name="portal_url",
            field=models.URLField(
                blank=True,
                help_text="Публичный адрес React-портала, например https://train.okurmen.kg — для кнопки «Открыть тренажёр».",
                max_length=300,
                validators=[
                    django.core.validators.URLValidator(
                        message="Укажите ссылку, начинающуюся с http:// или https://.",
                        schemes=["http", "https"],
                    )
                ],
                verbose_name="Адрес портала",
            ),
        ),
    ]
