# Generated by Django 6.1 on 2026-10-04 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0010_trainer_security_fields"),
        ("training", "0002_trainer_proxy"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingAttempt",
            fields=[],
            options={
                "verbose_name": "Попытка тренажёра",
                "verbose_name_plural": "Попытки тренажёров",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("testing.studentattempt",),
        ),
    ]
