# Generated by Django 6.1 on 2026-10-05 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0003_training_attempt_proxy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portalsettings",
            name="exam_url",
            field=models.URLField(
                blank=True,
                help_text="Куда ведёт кнопка «Экзаменге өтүү» — страница входа в экзамен по коду сессии (https://<сервер>/exam/). Пусто — кнопка скрыта.",
                max_length=500,
                validators=[
                    django.core.validators.URLValidator(
                        message="Укажите ссылку, начинающуюся с http:// или https://.",
                        schemes=["http", "https"],
                    )
                ],
                verbose_name="Ссылка на настоящий экзамен",
            ),
        ),
    ]
