# Generated by Django 6.1 on 2026-09-19 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Короткий заголовок новости.",
                        max_length=255,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Текст новости или объявления.", verbose_name="Текст"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("info", "Информация"),
                            ("important", "Важно"),
                            ("warning", "Предупреждение"),
                            ("event", "Мероприятие"),
                        ],
                        default="info",
                        help_text="Определяет иконку и цвет новости для тренеров.",
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[("all", "Всем"), ("selected", "Выбранным")],
                        default="all",
                        help_text="Кому показывать новость: всем тренерам или только выбранным.",
                        max_length=20,
                        verbose_name="Аудитория",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Неопубликованная новость не видна тренерам.",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="После этой даты новость перестаёт показываться тренерам. Можно оставить пустым.",
                        null=True,
                        verbose_name="Дата окончания",
                    ),
                ),
                (
                    "teachers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Тренеры, которым адресована новость (только при аудитории «Выбранным»).",
                        related_name="news",
                        to="users.teacher",
                        verbose_name="Тренеры",
                    ),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата прочтения"
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reads",
                        to="news.news",
                        verbose_name="Новость",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_reads",
                        to="users.teacher",
                        verbose_name="Тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прочтение новости",
                "verbose_name_plural": "Прочтения новостей",
                "ordering": ["-read_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("news", "teacher"), name="unique_news_teacher_read"
                    )
                ],
            },
        ),
    ]
