# Generated by Django 6.1 on 2026-09-19 18:17

import apps.news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                default=apps.news.models.default_news_expiry,
                help_text="После этой даты новость перестаёт показываться тренерам. По умолчанию новость публикуется 7 дней — можно изменить или оставить пустым.",
                null=True,
                verbose_name="Дата окончания",
            ),
        ),
    ]
