# Generated by Django 6.1 on 2026-09-25 09:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academy", "0017_student_enrollment_date"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScholarshipConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Одновременно может быть активна только одна конфигурация.",
                        verbose_name="Активна",
                    ),
                ),
                (
                    "award_mode",
                    models.CharField(
                        choices=[
                            ("monthly", "Раз в месяц (1-го числа)"),
                            ("twice_monthly", "Два независимых цикла (1-го и 15-го)"),
                        ],
                        default="monthly",
                        help_text="«Раз в месяц»: 1-го числа оценивается прошлый календарный месяц, 15-е число ничего не начисляет. «Два цикла»: 1-го и 15-го — два независимых распределения, каждое за свой завершённый месячный период и со своим лимитом получателей.",
                        max_length=20,
                        verbose_name="Режим начисления",
                    ),
                ),
                (
                    "max_recipients",
                    models.PositiveSmallIntegerField(
                        default=20,
                        help_text="Максимальное число уникальных получателей за один цикл.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                        verbose_name="Максимум получателей",
                    ),
                ),
                (
                    "attendance_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.40"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Вес посещаемости",
                    ),
                ),
                (
                    "homework_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.30"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Вес домашних заданий",
                    ),
                ),
                (
                    "feedback_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.30"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Вес оценки тренера",
                    ),
                ),
                (
                    "subject_aggregation",
                    models.CharField(
                        choices=[
                            ("equal", "Все предметы равны"),
                            ("lesson_weighted", "Пропорционально числу занятий"),
                        ],
                        default="equal",
                        help_text="Как баллы по предметам сводятся в один итоговый балл студента.",
                        max_length=20,
                        verbose_name="Агрегация предметов",
                    ),
                ),
                (
                    "late_homework_credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.50"),
                        help_text="Доля (0–1), которую получает ДЗ со статусом «Сдано с опозданием».",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Зачёт ДЗ, сданного с опозданием",
                    ),
                ),
                (
                    "min_overall_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Студенты с баллом ниже порога не получают стипендию. 0 — без порога.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Минимальный итоговый балл",
                    ),
                ),
                (
                    "min_marked_lessons",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Сколько занятий с отметкой посещаемости (без уважительных) нужно за период.",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Минимум отмеченных занятий",
                    ),
                ),
                (
                    "require_complete_feedback",
                    models.BooleanField(
                        default=True,
                        help_text="Если включено, студент без оценки тренера хотя бы по одному предмету получает статус «Неполные данные» и не участвует в распределении. Если выключено — отсутствующая оценка считается как 0 (никогда не как максимальный балл).",
                        verbose_name="Требовать оценку тренера по всем предметам",
                    ),
                ),
                (
                    "auto_approve",
                    models.BooleanField(
                        default=False,
                        help_text="Если выключено, сформированный рейтинг ждёт утверждения администратором.",
                        verbose_name="Утверждать автоматически",
                    ),
                ),
                (
                    "award_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Необязательно. Пусто — стипендия без денежной суммы.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Сумма стипендии",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Настройки стипендии",
                "verbose_name_plural": "Настройки стипендии",
                "ordering": ["-is_active", "-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="unique_active_scholarship_configuration",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ScholarshipPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "award_day",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1-е число"), (15, "15-е число")],
                        verbose_name="Цикл (день начисления)",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Начало периода")),
                ("period_end", models.DateField(verbose_name="Конец периода")),
                ("evaluation_date", models.DateField(verbose_name="Дата начисления")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик (ожидает утверждения)"),
                            ("approved", "Утверждён"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "max_recipients",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Максимум получателей",
                    ),
                ),
                (
                    "attendance_weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="Вес посещаемости"
                    ),
                ),
                (
                    "homework_weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="Вес ДЗ"
                    ),
                ),
                (
                    "feedback_weight",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=3,
                        verbose_name="Вес оценки тренера",
                    ),
                ),
                (
                    "subject_aggregation",
                    models.CharField(
                        choices=[
                            ("equal", "Все предметы равны"),
                            ("lesson_weighted", "Пропорционально числу занятий"),
                        ],
                        max_length=20,
                        verbose_name="Агрегация предметов",
                    ),
                ),
                (
                    "late_homework_credit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=3,
                        verbose_name="Зачёт ДЗ с опозданием",
                    ),
                ),
                (
                    "min_overall_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Минимальный балл"
                    ),
                ),
                (
                    "min_marked_lessons",
                    models.PositiveSmallIntegerField(
                        verbose_name="Минимум отмеченных занятий"
                    ),
                ),
                (
                    "require_complete_feedback",
                    models.BooleanField(verbose_name="Требовать оценку тренера"),
                ),
                (
                    "award_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Сумма стипендии",
                    ),
                ),
                (
                    "last_calculated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последний расчёт"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата утверждения"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Утвердил",
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="periods",
                        to="scholarships.scholarshipconfiguration",
                        verbose_name="Конфигурация",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сформировал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стипендиальный период",
                "verbose_name_plural": "Стипендиальные периоды",
                "ordering": ["-period_start", "-award_day"],
                "permissions": [
                    (
                        "generate_scholarshipperiod",
                        "Может формировать стипендиальный рейтинг",
                    ),
                    ("approve_scholarshipperiod", "Может утверждать стипендии"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScholarshipEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=210, verbose_name="ФИО")),
                (
                    "group_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Группа (на момент оценки)",
                    ),
                ),
                (
                    "course_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Курс (программа)"
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата начала обучения"
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Итоговый балл",
                    ),
                ),
                (
                    "attendance_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Посещаемость",
                    ),
                ),
                (
                    "homework_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Домашние задания",
                    ),
                ),
                (
                    "feedback_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Оценка тренера",
                    ),
                ),
                (
                    "lessons_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Занятий учтено"
                    ),
                ),
                (
                    "subjects_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Предметов учтено"
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Место"
                    ),
                ),
                (
                    "eligibility_status",
                    models.CharField(
                        choices=[
                            ("eligible", "Допущен"),
                            ("not_full_period", "Не весь период обучения"),
                            ("inactive", "Неактивен / на паузе"),
                            ("no_data", "Нет данных за период"),
                            ("incomplete_data", "Неполные данные"),
                            ("below_threshold", "Ниже порога"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Допуск",
                    ),
                ),
                (
                    "ineligibility_reason",
                    models.TextField(blank=True, verbose_name="Причина недопуска"),
                ),
                (
                    "data_warnings",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Предупреждения о данных"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="academy.group",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scholarship_evaluations",
                        to="academy.student",
                        verbose_name="Студент",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="scholarships.scholarshipperiod",
                        verbose_name="Период",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оценка студента",
                "verbose_name_plural": "Оценки студентов",
                "ordering": ["period", "rank", "-overall_score", "student_name"],
            },
        ),
        migrations.CreateModel(
            name="ScholarshipAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveIntegerField(verbose_name="Место")),
                ("award_date", models.DateField(verbose_name="Дата начисления")),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает утверждения"),
                            ("approved", "Утверждена"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата утверждения"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Утвердил",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scholarship_awards",
                        to="academy.student",
                        verbose_name="Студент",
                    ),
                ),
                (
                    "evaluation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="award",
                        to="scholarships.scholarshipevaluation",
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="scholarships.scholarshipperiod",
                        verbose_name="Период",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стипендия",
                "verbose_name_plural": "Стипендии",
                "ordering": ["-award_date", "rank"],
            },
        ),
        migrations.CreateModel(
            name="ScholarshipRunLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("generate", "Формирование"),
                            ("recalculate", "Пересчёт"),
                            ("approve", "Утверждение"),
                        ],
                        max_length=20,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("schedule", "По расписанию"),
                            ("admin", "Админ-панель"),
                            ("api", "API"),
                        ],
                        max_length=20,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "Успешно"),
                            ("skipped", "Пропущено"),
                            ("failed", "Ошибка"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Результат",
                    ),
                ),
                (
                    "award_day",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Цикл"
                    ),
                ),
                (
                    "award_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата начисления"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Сообщение")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Время"),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="run_logs",
                        to="scholarships.scholarshipperiod",
                        verbose_name="Период",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Журнал запусков",
                "verbose_name_plural": "Журнал запусков",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScholarshipSubjectScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_name",
                    models.CharField(max_length=100, verbose_name="Предмет (название)"),
                ),
                (
                    "lessons_attended",
                    models.PositiveIntegerField(default=0, verbose_name="Посещено"),
                ),
                (
                    "lessons_missed",
                    models.PositiveIntegerField(default=0, verbose_name="Пропущено"),
                ),
                (
                    "lessons_excused",
                    models.PositiveIntegerField(default=0, verbose_name="Уважительные"),
                ),
                (
                    "lessons_unmarked",
                    models.PositiveIntegerField(default=0, verbose_name="Без отметки"),
                ),
                (
                    "homework_required",
                    models.PositiveIntegerField(default=0, verbose_name="ДЗ задано"),
                ),
                (
                    "homework_completed",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=7,
                        verbose_name="ДЗ зачтено",
                    ),
                ),
                (
                    "feedback_expected",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Тренеров по предмету"
                    ),
                ),
                (
                    "feedback_received",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Оценок тренеров"
                    ),
                ),
                (
                    "attendance_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Посещаемость",
                    ),
                ),
                (
                    "homework_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="ДЗ",
                    ),
                ),
                (
                    "feedback_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Оценка тренера",
                    ),
                ),
                (
                    "subject_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Балл по предмету",
                    ),
                ),
                (
                    "aggregation_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="0 — предмет не учитывался (нет данных).",
                        max_digits=8,
                        verbose_name="Вес в итоговом балле",
                    ),
                ),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_scores",
                        to="scholarships.scholarshipevaluation",
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.subject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Балл по предмету",
                "verbose_name_plural": "Баллы по предметам",
                "ordering": ["evaluation", "subject_name"],
            },
        ),
        migrations.CreateModel(
            name="TrainerFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Прогресс",
                    ),
                ),
                (
                    "participation",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Активность на занятиях",
                    ),
                ),
                (
                    "discipline",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Дисциплина",
                    ),
                ),
                (
                    "understanding",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Понимание материала",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="Комментарий"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="scholarships.scholarshipperiod",
                        verbose_name="Период",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_feedback",
                        to="academy.student",
                        verbose_name="Студент",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trainer_feedback",
                        to="users.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scholarship_feedback",
                        to="users.teacher",
                        verbose_name="Тренер",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Изменил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оценка тренера",
                "verbose_name_plural": "Оценки тренеров",
                "ordering": [
                    "-period__period_start",
                    "student__last_name",
                    "subject__name",
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="scholarshipperiod",
            constraint=models.UniqueConstraint(
                fields=("award_day", "period_start"),
                name="unique_scholarship_cycle_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="scholarshipperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="scholarship_period_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="scholarshipperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("evaluation_date__gt", models.F("period_end"))),
                name="scholarship_evaluated_after_period_end",
            ),
        ),
        migrations.AddIndex(
            model_name="scholarshipevaluation",
            index=models.Index(
                fields=["period", "eligibility_status"], name="ix_scheval_period_status"
            ),
        ),
        migrations.AddIndex(
            model_name="scholarshipevaluation",
            index=models.Index(
                fields=["student", "period"], name="ix_scheval_student_period"
            ),
        ),
        migrations.AddConstraint(
            model_name="scholarshipevaluation",
            constraint=models.UniqueConstraint(
                fields=("period", "student"),
                name="unique_student_scholarship_evaluation",
            ),
        ),
        migrations.AddConstraint(
            model_name="scholarshipevaluation",
            constraint=models.UniqueConstraint(
                fields=("period", "rank"), name="unique_scholarship_evaluation_rank"
            ),
        ),
        migrations.AddIndex(
            model_name="scholarshipaward",
            index=models.Index(
                fields=["student", "status"], name="ix_schaward_student_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="scholarshipaward",
            constraint=models.UniqueConstraint(
                fields=("student", "period"), name="unique_student_scholarship_period"
            ),
        ),
        migrations.AddConstraint(
            model_name="scholarshipaward",
            constraint=models.UniqueConstraint(
                fields=("period", "rank"), name="unique_scholarship_award_rank"
            ),
        ),
        migrations.AddIndex(
            model_name="trainerfeedback",
            index=models.Index(
                fields=["period", "student"], name="ix_trfeedback_period_student"
            ),
        ),
        migrations.AddConstraint(
            model_name="trainerfeedback",
            constraint=models.UniqueConstraint(
                fields=("period", "student", "subject", "teacher"),
                name="unique_trainer_feedback_per_period",
            ),
        ),
    ]
