# Generated by Django 6.1 on 2026-09-26 02:48

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0002_default_configuration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarshipperiod",
            name="title",
            field=models.CharField(
                default="Стипендия", max_length=150, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="scholarshipperiod",
            name="award_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "1-е число"), (15, "15-е число")],
                help_text="Пусто — период создан вручную с произвольными датами.",
                null=True,
                verbose_name="Цикл (день начисления)",
            ),
        ),
        migrations.AlterField(
            model_name="scholarshipperiod",
            name="max_recipients",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Пусто — без ограничения.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Лимит стипендиатов",
            ),
        ),
        migrations.AlterField(
            model_name="scholarshiprunlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("generate", "Формирование"),
                    ("recalculate", "Пересчёт"),
                    ("approve", "Утверждение"),
                    ("edit", "Изменение периода"),
                    ("award", "Изменение списка стипендиатов"),
                ],
                max_length=20,
                verbose_name="Действие",
            ),
        ),
        migrations.AddConstraint(
            model_name="scholarshipperiod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("award_day__isnull", True)),
                fields=("period_start", "period_end"),
                name="unique_manual_scholarship_period",
            ),
        ),
    ]
