# Generated by Django 6.1 on 2026-09-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0017_student_enrollment_date"),
        ("scholarships", "0003_period_title_manual_dates_unlimited"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarshipperiod",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Пусто — все группы академии.",
                related_name="scholarship_periods",
                to="academy.group",
                verbose_name="Участвующие группы",
            ),
        ),
    ]
