# Generated by Django 6.1 on 2026-09-28 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0017_student_enrollment_date"),
        ("scholarships", "0004_period_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scholarshipaward",
            options={
                "ordering": ["-award_date", "rank"],
                "permissions": [
                    ("pay_scholarshipaward", "Может отмечать выдачу стипендий")
                ],
                "verbose_name": "Стипендия",
                "verbose_name_plural": "Стипендии",
            },
        ),
        migrations.AddField(
            model_name="scholarshipaward",
            name="paid_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Выплаченная сумма",
            ),
        ),
        migrations.AddField(
            model_name="scholarshipaward",
            name="paid_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата выплаты"
            ),
        ),
        migrations.AddField(
            model_name="scholarshipaward",
            name="paid_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Выдал",
            ),
        ),
        migrations.AddField(
            model_name="scholarshipaward",
            name="payment_comment",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Комментарий к выплате"
            ),
        ),
        migrations.AddField(
            model_name="scholarshipaward",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Наличные"),
                    ("bank", "Банковский перевод"),
                    ("other", "Другое"),
                ],
                max_length=10,
                verbose_name="Способ выплаты",
            ),
        ),
        migrations.AddField(
            model_name="scholarshipaward",
            name="payment_status",
            field=models.CharField(
                choices=[("unpaid", "Не выдано"), ("paid", "Выдано")],
                db_index=True,
                default="unpaid",
                max_length=10,
                verbose_name="Выплата",
            ),
        ),
        migrations.AlterField(
            model_name="scholarshiprunlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("generate", "Формирование"),
                    ("recalculate", "Пересчёт"),
                    ("approve", "Утверждение"),
                    ("edit", "Изменение периода"),
                    ("award", "Изменение списка стипендиатов"),
                    ("payment", "Выдача стипендий"),
                ],
                max_length=20,
                verbose_name="Действие",
            ),
        ),
        migrations.AddConstraint(
            model_name="scholarshipaward",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("payment_status", "unpaid"),
                    models.Q(("paid_at__isnull", False), ("status", "approved")),
                    _connector="OR",
                ),
                name="scholarship_award_paid_is_approved",
            ),
        ),
    ]
